name: tests

on: [push, pull_request]

jobs:
  test-windows:
    strategy:
      matrix:
        python-version: ["3.9","3.10"]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        shell: bash -l {0}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pip install
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Tests
        shell: bash -l {0}
        run: |
          pytest persistable
