name: tests

on: [push, pull_request]

jobs:
  test-linux-macos:
    strategy:
      matrix:
        python-version: ["3.9","3.10"]
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          python -m playwright install --with-deps
      - name: Run Setup.py
        run: |
          python -m setup build_ext --inplace
      - name: Run test 
        run: |
          pytest .


  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9","3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          python -m playwright install --with-deps
      - name: Run Setup.py
        shell: bash -l {0}
        run: |
          python -m setup build_ext --inplace
      - name: Run test 
        shell: bash -l {0}
        run: |
          pytest .



  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov
          python -m playwright install --with-deps
      - name: Run Setup.py
        run: |
          python -m setup build_ext --inplace --compile-with-cython-linetrace
      - name: Tests
        run: |
          pytest --cov persistable
      - name: Upload coverage results
        uses: codecov/codecov-action@v3
